path: yolo_ds  
train: train/images
val: val/images
test: test/images
 
names:
  0: "pedestrian"
  1: "person" 
  2: "bicycle"
  3: "car"
  4: "van"
  5: "truck"
  6: "tuktuk"
  7: "rickshaw"
  8: "bus"
  9: "bike"    
    